####
# Default job.
# This job simply defines the iOS image, some environment variables
# and stuff that all jobs should have
##
default: &defaultJob
  # Set the xcode version this virtual machine will use
  macos:
    xcode: "12.0.0"
  # We need to set this for RVM.
  shell: /bin/bash --login
# Default workflow will run on all branches except releases
default-workflow: &defaultWorkflow
  filters:
    branches:
      ignore:
        - /release\/.*$/
deploy-workflow: &deployWorkflow
  filters:
    branches:
      only:
        - /release\/.*$/

# Define the jobs we will be using
version: 2
jobs:
  test:
    <<: *defaultJob
    steps:
      - checkout
      - add_ssh_keys
      - restore_cache:
          key: gem-cache-{{ checksum "Gemfile.lock" }}-v2
      - restore_cache:
          keys: 
            - pods-cache-{{ .Branch }}-{{ checksum "Podfile" }}
            - pods-cache-{{ .Branch }}-
            - pods-cache
      - run:
          name: Install Bundler
          command: gem install bundler --user-install
      - run:
          name: Install Ruby tools
          command: bundle install --path vendor/bundle
      - run:
          name: Deactivate Cocoapods Verbose Logging
          command: ruby ./scripts/deactivate_verbose_logging.rb
      - run:
          name: Install CocoaPods
          command: bundle exec pod install
      - save_cache:
          key: gem-cache-{{ checksum "Gemfile.lock" }}-v2
          paths:
            - vendor/bundle
      - save_cache:
          key: pods-cache-{{ .Branch }}-{{ checksum "Podfile" }}
          paths:
            - Pods            
      - run:
          name: Run tests on iOS 13.5
          command: ./scripts/run_tests.sh 13.5
      - run:
          name: Run test on iOS 14.0
          command: ./scripts/run_tests.sh 14.0
      - run:
          name: Run Coverage Report
          command: ./scripts/run_coverage_report.sh
  lint:
    <<: *defaultJob
    steps:
      - checkout
      - add_ssh_keys
      - restore_cache:
          key: gem-cache-{{ checksum "Gemfile.lock" }}-v2
      - restore_cache:
          keys: 
            - pods-cache-{{ .Branch }}-{{ checksum "Podfile" }}
            - pods-cache-{{ .Branch }}-
            - pods-cache
      - run:
          name: Install Bundler
          command: gem install bundler --user-install
      - run:
          name: Install Ruby tools
          command: bundle install --path vendor/bundle
      - run:
          name: Install SwiftLint
          command: brew install swiftlint
      - run:
          name: Deactivate Cocoapods Verbose Logging
          command: ruby ./scripts/deactivate_verbose_logging.rb
      - run:
          name: Install CocoaPods
          command: bundle exec pod install
      - run:
          name: Run Pod Lint
          command: bundle exec pod lib lint AndesUI.podspec --allow-warnings --sources='https://cdn.cocoapods.org/'
      - run: 
          name: Run Swift lint
          command: swiftlint
  build:
    <<: *defaultJob
    steps:
      - checkout
      - add_ssh_keys
      - restore_cache:
          key: gem-cache-{{ checksum "Gemfile.lock" }}-v2
      - restore_cache:
          keys: 
            - pods-cache-{{ .Branch }}-{{ checksum "Podfile" }}
            - pods-cache-{{ .Branch }}-
            - pods-cache          
      - run:
          name: Install Bundler
          command: gem install bundler --user-install
      - run:
          name: Install Ruby tools
          command: bundle install --path vendor/bundle
      - run:
          name: Install CocoaPods
          command: bundle exec pod install
      # - run:
      #     name: Run Deploy
      #     command: ./scripts/run_deploy.sh
      - run:
          name: Build and publish precompiled
          command: |
              echo -e "plugin 'cocoapods-precompiled'\n$(cat Podfile)" > Podfile
              echo "gem 'cocoapods-precompiled', :git => '$COCOAPODS_PRECOMPILED_SOURCE'" >> Gemfile
              bundle install
              bundle exec pod precompiled create
              bundle exec pod precompiled publish          

# Define the full workflow.
workflows:
  version: 2
  test-lint:
    jobs:
      - test:
          <<: *defaultWorkflow
      - lint:
          <<: *defaultWorkflow
      - build:
          <<: *deployWorkflow
